// Code generated by protoc-gen-go.
// source: github.com/Rakanixu/elasticsearch/srv/proto/elasticsearch/elasticsearch.proto
// DO NOT EDIT!

/*
Package go_micro_srv_elasticsearch is a generated protocol buffer package.

It is generated from these files:
	github.com/Rakanixu/elasticsearch/srv/proto/elasticsearch/elasticsearch.proto

It has these top-level messages:
	Record
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
	SearchRequest
	SearchResponse
	QueryRequest
	QueryResponse
*/
package go_micro_srv_elasticsearch

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Record struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Data  string `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateRequest struct {
	Record *Record `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ReadRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ReadResponse struct {
	Record *Record `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadResponse) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type UpdateRequest struct {
	Record *Record `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateRequest) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type DeleteRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type SearchRequest struct {
	Index  string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type   string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Query  string `protobuf:"bytes,3,opt,name=query" json:"query,omitempty"`
	Limit  uint64 `protobuf:"varint,4,opt,name=limit" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,5,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SearchResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type QueryRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Query string `protobuf:"bytes,3,opt,name=query" json:"query,omitempty"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type QueryResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func init() {
	proto.RegisterType((*Record)(nil), "go.micro.srv.elasticsearch.Record")
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.elasticsearch.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.elasticsearch.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "go.micro.srv.elasticsearch.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "go.micro.srv.elasticsearch.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "go.micro.srv.elasticsearch.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "go.micro.srv.elasticsearch.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "go.micro.srv.elasticsearch.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "go.micro.srv.elasticsearch.DeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "go.micro.srv.elasticsearch.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "go.micro.srv.elasticsearch.SearchResponse")
	proto.RegisterType((*QueryRequest)(nil), "go.micro.srv.elasticsearch.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "go.micro.srv.elasticsearch.QueryResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Elasticsearch service

type ElasticsearchClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...client.CallOption) (*QueryResponse, error)
}

type elasticsearchClient struct {
	c           client.Client
	serviceName string
}

func NewElasticsearchClient(serviceName string, c client.Client) ElasticsearchClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.elasticsearch"
	}
	return &elasticsearchClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *elasticsearchClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Elasticsearch.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elasticsearchClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Elasticsearch.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elasticsearchClient) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Elasticsearch.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elasticsearchClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Elasticsearch.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elasticsearchClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Elasticsearch.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elasticsearchClient) Query(ctx context.Context, in *QueryRequest, opts ...client.CallOption) (*QueryResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Elasticsearch.Query", in)
	out := new(QueryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Elasticsearch service

type ElasticsearchHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
	Query(context.Context, *QueryRequest, *QueryResponse) error
}

func RegisterElasticsearchHandler(s server.Server, hdlr ElasticsearchHandler) {
	s.Handle(s.NewHandler(&Elasticsearch{hdlr}))
}

type Elasticsearch struct {
	ElasticsearchHandler
}

func (h *Elasticsearch) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.ElasticsearchHandler.Create(ctx, in, out)
}

func (h *Elasticsearch) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.ElasticsearchHandler.Read(ctx, in, out)
}

func (h *Elasticsearch) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.ElasticsearchHandler.Update(ctx, in, out)
}

func (h *Elasticsearch) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.ElasticsearchHandler.Delete(ctx, in, out)
}

func (h *Elasticsearch) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.ElasticsearchHandler.Search(ctx, in, out)
}

func (h *Elasticsearch) Query(ctx context.Context, in *QueryRequest, out *QueryResponse) error {
	return h.ElasticsearchHandler.Query(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0x51, 0xab, 0xd3, 0x30,
	0x14, 0xf6, 0x5e, 0xbb, 0x82, 0xe7, 0xde, 0x0e, 0x09, 0x32, 0x4a, 0x9f, 0x24, 0x2f, 0xdb, 0x7c,
	0x68, 0x61, 0xbe, 0xf9, 0xaa, 0x22, 0x2a, 0x0a, 0x56, 0xf4, 0x45, 0x10, 0xb2, 0x36, 0xdb, 0x82,
	0xdd, 0x52, 0x93, 0x54, 0xb6, 0x07, 0xff, 0xa7, 0x3f, 0xc7, 0x34, 0x49, 0xe7, 0x3a, 0x30, 0xce,
	0xdd, 0xbd, 0xe5, 0x1c, 0xbe, 0x7c, 0xdf, 0x77, 0x7a, 0xbe, 0x14, 0xde, 0x2d, 0x99, 0x5a, 0x35,
	0xf3, 0xb4, 0xe0, 0xeb, 0x2c, 0x27, 0xdf, 0xc8, 0x86, 0x6d, 0x9b, 0x8c, 0x56, 0x44, 0x2a, 0x56,
	0x48, 0x4a, 0x44, 0xb1, 0xca, 0xa4, 0xf8, 0x91, 0xd5, 0x82, 0x2b, 0x7e, 0xd4, 0xef, 0x55, 0xa9,
	0x41, 0xa0, 0x64, 0xc9, 0xd3, 0x35, 0x2b, 0x04, 0x4f, 0xf5, 0xad, 0xb4, 0x87, 0xc0, 0x9f, 0x21,
	0xcc, 0x69, 0xc1, 0x45, 0x89, 0x1e, 0xc1, 0x80, 0x6d, 0x4a, 0xba, 0x8d, 0xaf, 0x1e, 0x5f, 0x4d,
	0x1e, 0xe4, 0xb6, 0x40, 0x08, 0x02, 0xb5, 0xab, 0x69, 0x7c, 0x6d, 0x9a, 0xe6, 0x8c, 0x86, 0x70,
	0xcd, 0xca, 0xf8, 0xbe, 0xe9, 0xe8, 0x53, 0x8b, 0x29, 0x89, 0x22, 0x71, 0x60, 0x31, 0xed, 0x19,
	0xbf, 0x85, 0xe8, 0xb9, 0xa0, 0x44, 0xd1, 0x9c, 0x7e, 0x6f, 0xa8, 0x54, 0xe8, 0x19, 0x84, 0xc2,
	0x08, 0x19, 0xfe, 0x9b, 0x19, 0x4e, 0xff, 0xee, 0x2a, 0xb5, 0x96, 0x72, 0x77, 0x03, 0x3f, 0x84,
	0x61, 0x47, 0x26, 0x6b, 0xbe, 0x91, 0x14, 0xbf, 0x82, 0x9b, 0x9c, 0x92, 0xb2, 0x23, 0x3f, 0xdb,
	0x3b, 0x7e, 0x03, 0xb7, 0x96, 0xc8, 0x12, 0xdf, 0xc9, 0xa6, 0x9e, 0xf9, 0x53, 0x5d, 0x5e, 0x6e,
	0xe6, 0x8e, 0xcc, 0xcd, 0xfc, 0x1a, 0xa2, 0x17, 0xb4, 0xa2, 0x7f, 0xe8, 0xcf, 0x9f, 0x5a, 0x93,
	0x77, 0x54, 0x8e, 0xfc, 0x27, 0x44, 0x1f, 0x8d, 0x8f, 0xff, 0x27, 0xd7, 0x48, 0x7d, 0x45, 0xec,
	0x1c, 0xbf, 0x2d, 0xda, 0x6e, 0xc5, 0xd6, 0x4c, 0x99, 0x54, 0x04, 0xb9, 0x2d, 0xd0, 0x08, 0x42,
	0xbe, 0x58, 0x48, 0xaa, 0xe2, 0x81, 0x69, 0xbb, 0x0a, 0x4f, 0x60, 0xd8, 0xc9, 0xbb, 0x45, 0x8c,
	0xda, 0x6f, 0x27, 0x9b, 0x4a, 0x39, 0x03, 0xae, 0xc2, 0xef, 0xe1, 0xf6, 0x43, 0x2b, 0x70, 0x21,
	0x9f, 0x78, 0x0c, 0x91, 0xe3, 0xf3, 0x0b, 0xcf, 0x7e, 0x05, 0x10, 0xbd, 0x3c, 0xdc, 0x18, 0x22,
	0x10, 0xda, 0x58, 0xa2, 0xa9, 0x6f, 0xb1, 0xbd, 0x77, 0x90, 0x3c, 0x39, 0x05, 0xea, 0x96, 0x72,
	0x0f, 0x7d, 0x81, 0xa0, 0x8d, 0x27, 0x1a, 0xfb, 0x93, 0xb3, 0x7f, 0x09, 0xc9, 0xe4, 0xdf, 0xc0,
	0x3d, 0xb9, 0xf6, 0x6f, 0x23, 0xe6, 0xf7, 0xdf, 0xcb, 0xb4, 0xdf, 0xff, 0x51, 0x62, 0x8d, 0x84,
	0x0d, 0x9a, 0x5f, 0xa2, 0x97, 0x6b, 0xbf, 0xc4, 0x51, 0x6e, 0x8d, 0x84, 0x8d, 0x8e, 0x5f, 0xa2,
	0x97, 0x6e, 0xbf, 0x44, 0x3f, 0x89, 0x5a, 0xe2, 0x2b, 0x0c, 0x4c, 0x46, 0x90, 0xf7, 0xeb, 0x1e,
	0xc6, 0x32, 0x99, 0x9e, 0x80, 0xec, 0xf8, 0xe7, 0xa1, 0xf9, 0x4f, 0x3f, 0xfd, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0x10, 0x64, 0x61, 0xc3, 0xf8, 0x05, 0x00, 0x00,
}
